### ISSUE TITLE
Gatsby develop fails

### ISSUE THREAD

**Issue by Atchett** [StaticJsCMS/static-cms-gatsby-netlify-template#38]
Hi,

I've cloned the repo to run locally. And after installing the packages (npm install), and running gatsby develop I get the folloiwng error:

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant with the ISO 8601 standard for representation of dates and times using the Gregorian calendar.",
specifiedByURL: undefined, serialize: [function String], parseValue: [function String], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }).'.
Stacktrace was 'Error: Cannot create as TypeComposer the following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant with the ISO 8601 standard for representation of dates and times using the Gregorian calendar.",
specifiedByURL: undefined, serialize: [function String], parseValue: [function String], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }).
    at SchemaComposer.createTempTC (/Users/johnspurgin/Documents/Git/Gatsby/static-cms-gatsby-netlify-template/node_modules/graphql-compose/src/SchemaComposer.ts:624:11)
    at SchemaComposer.createTC (/Users/johnspurgin/Documents/Git/Gatsby/static-cms-gatsby-netlify-template/node_modules/graphql-compose/src/SchemaComposer.ts:580:66)
    at SchemaComposer.add (/Users/johnspurgin/Documents/Git/Gatsby/static-cms-gatsby-netlify-template/node_modules/graphql-compose/src/SchemaComposer.ts:876:21)
    at createSchemaComposer (/Users/johnspurgin/Documents/Git/Gatsby/static-cms-gatsby-netlify-template/node_modules/gatsby/src/schema/schema-composer.ts:21:18)
    at build (/Users/johnspurgin/Documents/Git/Gatsby/static-cms-gatsby-netlify-template/node_modules/gatsby/src/schema/index.js:140:26)
    at buildSchema (/Users/johnspurgin/Documents/Git/Gatsby/static-cms-gatsby-netlify-template/node_modules/gatsby/src/services/build-schema.ts:19:3)'

I have googled around and have seen the issues related to graphql versions and I have tried various "fixes":

- update dependencies - npm update
- remove node_modules & package-lock.json and re-install
- gatsby clean etc

Nothing appears to fix.

my local gatsby version: "gatsby -v"

Gatsby CLI version: 5.12.4
Gatsby version: 5.12.9

I don't have an example repo - it's simply a clone of this one, nothing added or removed.

Any ideas?

Thank you in advance.

**Comment by KaneFreeman** [comment]
This appears to be an issue when using `npm` to install the dependencies. I'll try to take a look at it. For now I recommend using the `yarn` commands instead.
